spring:
  application:
    name: aggr
  datasource:
    url: jdbc:h2:mem:aggregator
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    consul:
      config:
        enabled: false
      enabled: false
server:
  port: 8085
service:
  demography:
    api:
      url: http://localhost:8096